linters-settings:
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - paramTypeCombine
      - hugeParam
  revive:  # replacement for golint and nosnakecase
    rules:
      - name: var-naming

linters:
  enable-all: true
  disable:
    - prealloc
    - gochecknoglobals
    - err113       # formerly goerr113
    - funlen
    - mnd          # formerly gomnd
    - gci
    - unconvert
    - wrapcheck
    - lll
    - dupl
    - goconst
    - unparam
    - goimports
    - godox
    - varnamelen # doesn't really match our variable naming style
    - tenv
    - depguard
    - exhaustive
    - gocyclo
    - cyclop

run:
  modules-download-mode: vendor
  tests: false

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
