linters-settings:
  govet:
    check-shadowing: true
    enable:
      - fieldalignment  # replacement for maligned
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - paramTypeCombine
      - hugeParam
  revive:  # replacement for golint and nosnakecase
    rules:
      - name: var-naming

linters:
  enable-all: true
  disable:
    - prealloc
    - gochecknoglobals
    - goerr113
    - funlen
    - gomnd
    - gci
    - unconvert
    - wrapcheck
    - lll
    - dupl
    - goconst
    - unparam
    - goimports
    - godox
    - exhaustivestruct
    - varnamelen # doesn't really match our variable naming style
    # Explicitly disable all deprecated linters
    - deadcode     # deprecated: use unused
    - structcheck  # deprecated: use unused
    - varcheck     # deprecated: use unused
    - ifshort      # deprecated: no replacement
    - golint       # deprecated: use revive
    - interfacer   # deprecated: no replacement
    - maligned     # deprecated: use govet fieldalignment
    - scopelint    # deprecated: use exportloopref
    - nosnakecase  # deprecated: use revive

run:
  modules-download-mode: readonly
  tests: false

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.30.x # use the fixed version to not introduce new linters unexpectedly
