version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: make test
      - run: make lint

workflows:
  version: 2

  deployment-pipeline:
    jobs:
      - test
